# Generated by Django 5.1 on 2024-09-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_rename_name_userinfo_username_alter_admin_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='role',
            field=models.SmallIntegerField(choices=[(1, 'Admin'), (2, 'Employee')], default=2),
        ),
    ]
