# Generated by Django 5.1 on 2024-09-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_admin_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='role',
            field=models.SmallIntegerField(choices=[(1, 'Manager'), (2, 'Employee')], default=2, verbose_name='Role'),
        ),
    ]
